### ISSUE TITLE
Tracking issue: Benching different types of hashes for zk friendly signature scheme

### ISSUE THREAD

**Issue by codeblooded1729** [0xmozak/mozak-vm#1148]
- [x] Poseidon   https://github.com/0xmozak/mozak-vm/pull/1112
- [x] Keccak256  https://github.com/0xmozak/mozak-vm/pull/1149
- [x] Sha256 https://github.com/0xmozak/mozak-vm/pull/1234
