### ISSUE TITLE
Tracking issue: Complete Self Prog ID feature.

### ISSUE THREAD

**Issue by codeblooded1729** [0xmozak/mozak-vm#1703]
- [ ] Allow native programs access `ProgramIdenitifier` of their guest program https://github.com/0xmozak/mozak-vm/pull/1701
- [ ] remove the need to pass `self-prog-id` in CLI for proving guest programs (Since it can be extracted out of their ELF)
- [ ] Tie this `ProgramIdentifier` to the final recursive Prover. https://github.com/0xmozak/mozak-vm/pull/1607
